readmeio/httpsnippet

src/targets/python/helpers.js
src/targets/python/requests.js
test/fixtures/output/python/requests/application-form-encoded.py
test/fixtures/output/python/requests/application-json.py
test/fixtures/output/python/requests/cookies.py
test/fixtures/output/python/requests/full.py
test/fixtures/output/python/requests/headers.py
test/fixtures/output/python/requests/jsonObj-multiline.py
test/fixtures/output/python/requests/jsonObj-null-value.py
test/fixtures/output/python/requests/multipart-data.py
test/fixtures/output/python/requests/multipart-file.py
test/fixtures/output/python/requests/multipart-form-data.py
test/fixtures/output/python/requests/text-plain.py

This cleans up the snippets that are coming from the Python `requests` client to:
* With this work, `false`, `true`, and `null` are now being translated into the Python-proper literals of `False`, `True`, and `None`.

fix: cleaner python json snippets

---

src/targets/node/fetch.js
test/fixtures/output/node/fetch/application-form-encoded.js
test/fixtures/output/node/fetch/full.js
test/fixtures/output/node/fetch/multipart-form-data.js

The `node-fetch` target was originally sending `x-www-form-urlencoded` as a JSON object to `body` when it should be encoded with `URLSearchParams`.

fix: updating the node-fetch target to handle form-urlencoded requests

---

src/targets/node/fetch.js
test/fixtures/output/node/fetch/application-form-encoded.js
test/fixtures/output/node/fetch/full.js

`node-fetch` can accept URLSearchParams directly without having to translate it to a string first.

fix: simplifying node-fetch snippets with urlsearchparams

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json
src/targets/node/fetch.js
test/targets/node/fetch.js

Original Ticket: https://app.asana.com/0/1199087650851461/1198986894847661
This PR adds the flag `useObjectBody` to `httpsnippet.convert`'s second parameter, `options`. That flag causes the request body to be included as an object literal wrapped in `JSON.stringify`, as opposed to showing the object as a string literal.
**Old Format**
**New Format**
Next up we need to get api-explorer to use this version of the library, and enable this flag.

feat: add useObjectBody flag for better request body readability

---

package-lock.json
package.json
src/targets/ruby/native.js
test/fixtures/output/ruby/native/https.rb

The option `http.verify_mode = OpenSSL::SSL::VERIFY_NONE` in the ruby native target bypasses ssl certificate verification. This changes that setting to `http.verify_mode = OpenSSL::SSL::VERIFY_PEER`, a more secure option.
It is also the default option, but I think being explicit has its benefits, such as making the option visible for newcomers who have certificate issues.

switch ruby ssl from verify_none to verify_peer

---

src/targets/javascript/fetch.js
test/fixtures/output/javascript/fetch/application-form-encoded.js
test/fixtures/output/javascript/fetch/full.js
test/targets/javascript/fetch.js

JS `fetch` body needs to be a string, and we were sending objects on `x-www-url-formencoded` requests. This fixes that by wrapping those objects in `new URLSearchParams`.

fix: not sending form urlencoded properly in JS fetch snippets

---

src/targets/shell/curl.js
test/targets/shell/curl.js

This fixes a case where because we pass `escapeQueryStrings: false` to HTTPSnippet and don't escape query strings (instead relying on OAS style configurations), query strings in cURL snippets like `[["$attributed_flow","=","FLOW_ID"]]` wouldn't be escaped if the OAS doesn't use styles, resulting in a cURL snippet that couldn't actually be run.
```shell
$ curl --request GET \
>   --url 'https://mockbin.org/?where=[["$attributed_flow","=","FLOW_ID"]]' \
>   --header 'Accept: application/json'
curl: (3) [globbing] bad range specification in column 29
```
This fixes this problem by adding a new option to the cURL target called `escapeBrackets` that when present will manually escape `[` and `]`in the `fullUrl` data that it uses to chuck into the `--url` argument.
Resolves CX-347

fix: add new option for escaping brackets in curl snippets

---

README.md
src/index.js
src/targets/node/fetch.js
src/targets/node/request.js
src/targets/node/unirest.js
src/targets/php/curl.js
test/fixtures/output/node/fetch/cookies.js
test/fixtures/output/node/fetch/full.js
test/targets.js
test/targets/shell/curl.js

With the work done in https://github.com/readmeio/oas-to-har/pull/17 to ensure that query parameters are always properly encoded it was discovered that cookie parameters were being double encoded: once in `oas-to-har` and again here. Since this is obviously bad, I've refactored our existing custom `escapeQueryStrings` option to be `harIsAlreadyEncoded` (defaulting to false) so that we can now control both query string and cookie encoding behavior.
In the process of doing this I've slightly refactored a couple targets to no longer do their own cookie encoding as it's already being done in the `HTTPSnippet` constructor when it builds up a list of `allHeaders`. This refactor also allows us to not have to pass an option to `HTTPSnippet` and also to the target itself to control encoding …

feat: adding a new `harIsAlreadyEncoded` option

---

__tests__/__fixtures__/output/python/requests/application-form-encoded.py
__tests__/__fixtures__/output/python/requests/application-json.py
__tests__/__fixtures__/output/python/requests/cookies.py
__tests__/__fixtures__/output/python/requests/full.py
__tests__/__fixtures__/output/python/requests/headers.py
__tests__/__fixtures__/output/python/requests/http-insecure.py
__tests__/__fixtures__/output/python/requests/jsonObj-multiline.py
__tests__/__fixtures__/output/python/requests/jsonObj-null-value.py
__tests__/__fixtures__/output/python/requests/multipart-data.py
__tests__/__fixtures__/output/python/requests/multipart-file.py
__tests__/__fixtures__/output/python/requests/multipart-form-data-no-params.py
__tests__/__fixtures__/output/python/requests/multipart-form-data.py
__tests__/__fixtures__/output/python/requests/nested.py
__tests__/__fixtures__/output/python/requests/query-encoded.py
__tests__/__fixtures__/output/python/requests/query.py
__tests__/__fixtures__/output/python/requests/short.py
__tests__/__fixtures__/output/python/requests/text-plain.py
__tests__/targets/python/requests.js
src/targets/python/requests.js

Cleans up the Python [requests](https://docs.python-requests.org/en/latest/) library snippets by utilizing the HTTP method accessors they provide.
**Before:**
```py
response = requests.request("POST", url, data=payload, headers=headers)
```
**After:**
```py
response = requests.post(url, data=payload, headers=headers)
```
No testing needed if CI is all ✅

feat: cleaner python requests code by using available http accessors

---

__tests__/__fixtures__/output/javascript/axios/application-form-encoded.js
__tests__/__fixtures__/output/javascript/axios/full.js
__tests__/__fixtures__/output/node/axios/application-form-encoded.js
__tests__/__fixtures__/output/node/axios/full.js
src/targets/javascript/axios.js
src/targets/node/axios.js

| 🚥 Fix https://github.com/readmeio/api/issues/436 |
| :-- |
This updates the snippets that we generate for [Axios](https://npm.im/axios) on JS to properly send payloads for `x-www-form-urlencoded` requests.
I'm also updating the Node Axios snippets to have some breathing room where we set up `URLSearchParams` and to also have a consistent trailing comma where it's applied to the payload.
See tests.

fix: js + axios snippets for `x-www-form-urlencoded` are wrong

---

__tests__/__fixtures__/output/r/httr/query-encoded.r
src/targets/r/httr.js

| 🚥 Fix RM-4465 |
| :-- |
A user reported this issue to us on our docs where query strings for R wouldn't be properly concatenated with a comma:
```r
library(httr)
url <- "https://dash.readme.com/api/v1/categories"
queryString <- list(
perPage = "10"    # this is missing a comma
page = "1",       # this shouldn't have a comma
)
response <- VERB("GET", url, add_headers('Authorization' = 'Basic REDACTED'), query = queryString, content_type("application/octet-stream"))
content(response, "text")
```
Digging into it, because the `httr` target was calculating the total number of query strings before removing the `key` the count would always be off for a query string of two parameters.
Reason the existing `query` fixture tests didn't have this problem was because its query string evaluates to `{ …

fix: issue where query strings in R wouldn't be properly concatenated

---

src/targets/python/requests/client.ts
src/targets/python/requests/fixtures/multipart-data.py
src/targets/python/requests/fixtures/multipart-file.py

| 🚥 Fix RM-5624 |
| :-- |
This updates the Python snippets to do load files, when we have `contentType` info int the HAR, with `(open("squad.csv", "rb"), "squad.csv", "text/csv")` instead of `open("squad.csv", "rb")`.
Axios tests are still broken with this, but if Python and the other integration tests are passing then this should be good.

fix: surfacing content type info when running `open()` in python

---

docker-compose.yml

| 🚥 Fixes #183 |
| :---------------- |
- The integration tests are now set not to run if `NODE_ENV == test`, which they are by default. Set `NODE_ENV` to `integration` when running integration tests

Reënable integration tests

---

src/helpers/__snapshots__/utils.test.ts.snap
src/helpers/utils.test.ts
src/targets/http/target.ts

| 🚥 Resolves N/A|
| :------------------- |
The `default` for http does not match any client IDs. This will cause issues when trying to generate a code sample using `.convert` and trying to use the `default` as the second param.
You can run the following typescript code
```TypeScript
import { availableTargets } from "@readme/httpsnippet";
const languageTargets = availableTargets();
const httpLanguageTarget = languageTargets.find(
(target) => target.key === "http",
); // Can add a ! at the end for type checker
snippet = new HTTPSnippet({
bodySize = -1,
cookies: [],
headers: [],
headersSize: -1,
httpVersion: "HTTP/1.1",
method: "GET",
queryString: [],
url: "https://www.example.com/foo",
}).convert(httpLanguageTarget, httpLanguageTarget.default)
```
```
TypeError: Cannot destructure property …
```

Fix default http client

---

README.md
src/targets/index.test.ts
src/targets/index.ts

In `@readme/oas-to-snippet` right now the way we're installing `httpsnippet-client-api` is the following:
```js
addTargetClient('node', HTTPSnippetSimpleApiClient);
```
This works normally but because we'd love to have folks create their own client plugins and give us NPM packages we don't want to have to supply a target for these plugins when it's easier if the plugin can define that themselves.
The work I've done here is to create a new `addClientPlugin` hook for installing a one of these target + client combinations and then also a new `ClientPlugin` interface that combines the two so we can enforce that plugins are properly defined:
```ts
interface ClientPlugin {
client: Client;
target: TargetId;
}
```
With all this work we'll be able to now execute the folllowing to install …

feat: creation of a new interface for combined target + client installation

---

src/helpers/__snapshots__/utils.test.ts.snap
src/targets/csharp/restsharp/client.ts
src/targets/index.ts
src/targets/javascript/axios/client.ts
src/targets/node/axios/client.ts
src/targets/node/fetch/client.ts
src/targets/node/request/client.ts
src/targets/ocaml/cohttp/client.ts
src/targets/php/guzzle/client.ts
src/targets/python/requests/client.ts
src/targets/shell/httpie/client.ts

This create a new optional `installation` property on clients that allows us to document how to install that given client. We have this same work in `@readme/oas-to-snippet`[^1] but because wth https://github.com/readmeio/httpsnippet/pull/206 I'm moving some of this work to be loaded as a plugin in that library it makes more sense for these installation instructions to live as close to the client snippet generation code as possible.
And because this is adding an optional property to the client config I'm not going to treat this as a breaking change.
[^1]: https://github.com/readmeio/oas/blob/main/packages/oas-to-snippet/src/supportedLanguages.ts#L43

feat: client config for documenting installation instructions

---

src/targets/shell/curl/client.ts
src/targets/shell/curl/fixtures/short-options.sh

One of the code paths was not using the `arg()` helper.

fix(cURL): short `-d` option handling

---

README.md
package-lock.json
package.json
src/fixtures/runCustomFixtures.ts
src/index.test.ts
src/index.ts
src/targets/index.test.ts

In September of last year I reworked this library[^1] off `node-fetch` and the funky non-native `FormData` object it ships to only support native `FormData` -- in the process making code snippet generation asynchronous. Unfortunately this async work is causing us some headaches on integrating it into our API Explorer.
I started to dig in to trying to make `formdata-to-string` synchronous and realized... why bother? We have the HAR, we can generate everything we need for a multipart boundary from that.
[^1]: https://github.com/readmeio/httpsnippet/pull/199

feat: heavily simplify multipart formdata snippet generation

---

src/fixtures/runCustomFixtures.ts
src/index.ts
src/targets/index.test.ts

I had DX concerns about the `string[] | string` setup in the `.convert()` method and talked offline with @erunion and agreed that it should always return a `string[]`, so this PR makes that change. This is a breaking change.
Is this everything? I saw this line below but I think it's unrelated so I left it, but let me know if I'm wrong about this.
https://github.com/readmeio/httpsnippet/blob/fc92e4000714ec677bbf712fc9537fd616e8ae65/src/targets/index.ts#L41

fix(breaking): always return array

---

src/targets/swift/urlsession/client.ts
src/targets/swift/urlsession/fixtures/application-form-encoded.swift
src/targets/swift/urlsession/fixtures/application-json.swift
src/targets/swift/urlsession/fixtures/cookies.swift
src/targets/swift/urlsession/fixtures/custom-method.swift
src/targets/swift/urlsession/fixtures/full.swift
src/targets/swift/urlsession/fixtures/headers.swift
src/targets/swift/urlsession/fixtures/http-insecure.swift
src/targets/swift/urlsession/fixtures/indent-option.swift
src/targets/swift/urlsession/fixtures/json-null-value.swift
src/targets/swift/urlsession/fixtures/jsonObj-multiline.swift
src/targets/swift/urlsession/fixtures/jsonObj-null-value.swift
src/targets/swift/urlsession/fixtures/multipart-data.swift
src/targets/swift/urlsession/fixtures/multipart-file.swift
src/targets/swift/urlsession/fixtures/multipart-form-data-no-params.swift
src/targets/swift/urlsession/fixtures/multipart-form-data.swift
src/targets/swift/urlsession/fixtures/nested.swift
src/targets/swift/urlsession/fixtures/postdata-malformed.swift
src/targets/swift/urlsession/fixtures/pretty-option.swift
src/targets/swift/urlsession/fixtures/query-encoded.swift
src/targets/swift/urlsession/fixtures/query.swift
src/targets/swift/urlsession/fixtures/short.swift
src/targets/swift/urlsession/fixtures/text-plain.swift
src/targets/swift/urlsession/fixtures/timeout-option.swift

- Add query logic in Swift
- URLQueryItem has url encode logic
I fixed test code in `/httpsnippet/src/targets/swift/urlsession/fixtures/`
`npm run test`

Add query logic in Swift

---

.github/workflows/ci.yml
package.json

refactors our CI a bit:
- don't use `--write` flag when running prettier in CI
- splits out linting + tests

ci: shuffle a few things around

---

src/helpers/__snapshots__/utils.test.ts.snap
src/index.ts
src/targets/csharp/restsharp/client.ts
src/targets/index.test.ts
src/targets/index.ts
src/targets/javascript/axios/client.ts
src/targets/node/axios/client.ts
src/targets/ocaml/cohttp/client.ts
src/targets/php/guzzle/client.ts
src/targets/python/requests/client.ts
src/targets/shell/httpie/client.ts

We're working on some enhancements for HTTP snippet generation for external partners and need to make plugin installation strings dynamic -- this reworks how `installation` is set up on a client basis to allow for this.

feat: support for making installation string generation dynamic

---

src/fixtures/runCustomFixtures.ts
src/helpers/code-builder.ts
src/helpers/escape.ts
src/helpers/headers.ts
src/helpers/reducer.ts
src/helpers/shell.ts
src/helpers/utils.ts
src/index.test.ts
src/index.ts
src/targets/index.ts
src/targets/php/helpers.ts
src/targets/powershell/common.ts
tsconfig.json

Enables `isolatedDeclarations` in our TS config for improved types.

feat: enabling `isolatedDeclarations`
